version: '3.1'

services:
  mysql-standalone:
    image: mysql:8.0.27
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: taskex
      MYSQL_PASSWORD: root
      restart: always



  app:
    image: morboui/socks-mysql:socks-mysql5
    container_name: application
    ports:
      - "8080:8080"
    environment:
          SPRING_DATASOURCE_URL: jdbc:mysql://raiff-mysql-standalone-1:3306/taskex
          SPRING_DATASOURCE_USERNAME: "root"
          SPRING_DATASOURCE_PASSWORD: "root"
    build:
          context: "./"
          dockerfile: "DockerFile"
    depends_on:
            - mysql-standalone
    links:
      - mysql-standalone
    restart: always
