version: '3.1'

services:
  postgres:
    build:
      context: db
      dockerfile: Dockerfile
    image: 'docker-postgres'
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD=root
    volumes:
      - "db-data:/var/lib/postgresql/data"



  app:
    build:
      context: app
      dockerfile: DockerFile
    image: morboui/socks-app
    ports:
      - "8080:8080"
    environment:
          - PORT=8080
          - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres/postgres
    depends_on:
            - postgres

volumes:
  db-data:
